### PR TITLE
Show vi mode in prompt

### PR DESCRIPTION
**Pull request by herder**
This adds a visual indicator of the vi mode in psql among others.

### CODE REVIEW

**Comment by lfilho** [comment]
I've set this value manually but didn't see any indicator on the screen. Can you provide more details and maybe a screenshot? Thanks

**Comment by herder** [comment]
Hi, my memory is a bit hazy on this one, but it is supposed to set the visual indicator for readline-using programs (psql being one of them)

Here is a transcript from a session where I set it on and off in a bash shell (note the `+` indicator):
```shell
niklash@gew1-host:~$ bind 'set show-mode-in-prompt on'
bind 'set show-mode-in-prompt on'
+niklash@gew1-host:~$
+niklash@gew1-host:~$ bind 'set show-mode-in-prompt off'
bind 'set show-mode-in-prompt off'
niklash@gew1-host:~$
```

**Comment by lfilho** [comment]
I don't even have `bind` command. You mentioned bash shell. This repo is for zsh shell.

I tried running just `set show-mode-in-prompt off` and `set show-mode-in-prompt on` but didn't see any difference in my zsh shell with my current theme...

**Comment by herder** [comment]
This is not for the shell, but for other programs which use the GNU readline library (psql, for example): when this flag is set, the prompt gets a mode indicator. So it's not for zsh, but lots of other CLI programs :)

See https://tiswww.case.edu/php/chet/readline/readline.html#IDX40

**Comment by herder** [comment]
Closing this due to inactivity :)

**Pull request closed without merging**
