### PR TITLE
Vimshell

### PR DESCRIPTION
**Pull request by rocknrollMarc**
Shell inside of vim and I made it look nice!
start it with ,s.

vimshell

Wow and in Macvim, even more usefull, might even use it now ;)

### CODE REVIEW

**Comment by skwp** [comment]
wow there's a lot of stuff here. Unfortunately I can't take it all. The shell looks interesting - would you be able to make a PR just including the shell stuff possibly?

**Comment by rocknrollMarc** [comment]
Ok sure in the end im using yadr to and am looking around for cool stuff. Yes the shell is really cool actualy even with tmux

**Comment by rocknrollMarc** [comment]
ill make a feature branch ok and repush

**Comment by skwp** [comment]
Thanks closing this PR as it has all kinds of things conflated

**Pull request closed without merging**
