### PR TITLE
feat(*): Colorized irb prompt

### PR DESCRIPTION
**Pull request by plribeiro3000**
The [`irb`](https://github.com/skwp/dotfiles/tree/master/irb) configuration folder was added 6 years ago.

The gem [`jazz_hands`](https://github.com/nixme/jazz_hands) last commit was 7 years ago. I did a fork a while ago called [`jazz_fingers`](https://github.com/plribeiro3000/jazz_fingers). Most of the code being added and maintained here was ported to the new gem.

I'm happy to discuss this move further if needed.

### CODE REVIEW

**Comment by lfilho** [comment]
Hey, thanks for your PR!

Few questions:

1. Don't you need to list jazz fingers somewhere for installation? I only see it being required out of the blue, without being installed anywhere.
2. Why should we do this change? What is wrong with current setup or what other benefits / improvements your proposed solutions bring? And at what cost (any trade-offs or limitations)?

Thank you!

**Comment by plribeiro3000** [comment]
Hello @lfilho!

Thanks for the fast feedback.

1. Dunno where i should do that. Could you point me the best place/current standard?

2. The current setup is 6 years old
- `jazz_hands` is not maintained anymore:
  - It depends on an old version of `pry`
  - It depends on `pry-rails` so if you are not using rails it loads unnecessary code
  - It depends on `awesome_print` which is not maintained anymore
- `jazz_fingers` is active
  - it is uptodate with latest version of `pry`
  - it does not depend on `pry-rails`
  - it depends on `amazing_print` which is an uptodate fork of `awesome_print`

Before, all the configurations would be in this repo, making it easier to maintain, and now it will be in a gem (`jazz_fingers`)
So it is not going to be as simple as before to update it but the dependencies version lock that `bundler` has will give this project less issues with compatibility regarding old versions of `ruby` and gems.

**Comment by lfilho** [comment]
Hmmm I'm a bit on the fence with this one. This repo is used by thousands of people and it seems this would break and existing behavior / configuration with no alternative to have it retrocompatible.

@skwp ?

**Comment by plribeiro3000** [comment]
@lfilho Makes sense. Dunno about making it backwards compatible but i'm willing to try if thats the case.
BTW, since i've started using this some years ago, this part never worked correctly to me since its to old.

**Comment by plribeiro3000** [comment]
@lfilho The current setup uses outdated libraries. Maybe if force a new `bundle install` after updating yadr?

This should be enough to make it backwards compatible for everyone since all the code removed here is now inside the gem `jazz_fingers`. WDYT?

**Comment by lfilho** [comment]
This still don't seem well tested and giving us a confidence it won't break things, but on the other hand it seems the blast radius is small and it's a two-way door decision -- we can always revert this commit if things go awry. So let's merge and see what happens :) 

Thanks for the contribution

**Comment by plribeiro3000** [comment]
Sure @lfilho. Let me know if anything breaks and that you need me to do something about it.

**Pull request merged**
