### PR TITLE
fix: Update Homebrew install method

### LINKED ISSUE #844: Homebrew halts installation on a fresh MacOS
Hey,

When installing YADR on a fresh installation I noticed that Homebrew fails because the installation method has changed. I am attaching the screenshot for the same. 

I can open a PR for the required change. 😃 

image

### PR DESCRIPTION
**Pull request by vovinacci**
Closes #844

### CODE REVIEW

**Comment by vovinacci** [comment]
@lfilho Sorry for pushing a bit. That fixes fresh installs. Tested that - looks good. Shall we merge it?

**Comment by lfilho** [comment]
Hey @vovinacci sorry, I had missed this notification. But it looked like you commited the `install.sh` by mistake? I tried deleting it from the pull request but instead i deleted the file itself (my bad!). If you could just fix up and only change the Rakefile. I'll merge it right after

Thanks for doing it

**Comment by vovinacci** [comment]
@lfilho Thank you for the comment. I've changed `install.sh` mode (added `+x`), however missed to write about this change. This made local run slightly easier as you don't need to invoke shell explicitly to run the script. My bad, sorry. Reverted that change. Thanks again!

**Comment by lfilho** [comment]
Thanks!

**Pull request merged**
