### PR TITLE
ydv -u should use url

### PR DESCRIPTION
**Pull request by salamanderrex**
For ydv -u
we should use full url

### CODE REVIEW

**Comment by lfilho** [comment]
Why should we? Could you elaborate more? Is it not working as it is? Or why is it better?

**Comment by skwp** [comment]
are people even using these scripts? i haven't tested them in forever

**Comment by lfilho** [comment]
Personally, I've never used them. It's the kind of the thing we do so seldomly that it's easier just to delete (or add) a plugin's `Vundle` line 😇

**Comment by skwp** [comment]
I agree we should delete and tell ppl to use the vundle directly

**Comment by salamanderrex** [comment]
If you try ydv -u airblade/vim-rooter, it does not work. 
You need to input full url to do the deletion.
ydv -u https://github.com/airblade/vim-rooter

**Pull request closed without merging**
